<a href="https://colab.research.google.com/github/Mayakshanesht/Autonomous_Driving_Lecture_resources/blob/Perception/01_Upsampling_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing libraries

In [1]:
import numpy as np
import keras

# Defining the Input

In [ ]:
X = np.array([[1,2],
              [3,4]], dtype= np.uint8)
X = X.reshape((1,2,2,1))

## Configuring the layers

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.UpSampling2D(input_shape= (2,2,1)))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_4 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


### Predicting the output

In [ ]:
yhat = model.predict(X)
yhat = yhat.reshape((4,4))
yhat

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [3., 3., 4., 4.],
       [3., 3., 4., 4.]], dtype=float32)

# Using different model

In [ ]:
model2 = keras.models.Sequential()
model2.add(keras.layers.UpSampling2D(input_shape= (2,2,1), size= (3,3)))
model2.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_5 (UpSampling2 (None, 6, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


### Predicting the output

In [ ]:
yhat = model2.predict(X)
yhat = yhat.reshape((6,6))
yhat

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [3., 3., 3., 4., 4., 4.],
       [3., 3., 3., 4., 4., 4.],
       [3., 3., 3., 4., 4., 4.]], dtype=float32)

# Different Model

In [ ]:
visible = keras.layers.Input(shape= (2,2,1))
outputs = keras.layers.UpSampling2D(input_shape= (2,2,1),
                                   size= (4,4),
                                   interpolation= 'bilinear')(visible)
model3 = keras.models.Model(inputs= visible, outputs= outputs)
model3.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 2, 2, 1)           0         
_________________________________________________________________
up_sampling2d_9 (UpSampling2 (None, 8, 8, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


### Predicting the model

In [ ]:
yhat = model3.predict(X)
yhat = yhat.reshape((8,8))
yhat

array([[1.  , 1.25, 1.5 , 1.75, 2.  , 2.  , 2.  , 2.  ],
       [1.5 , 1.75, 2.  , 2.25, 2.5 , 2.5 , 2.5 , 2.5 ],
       [2.  , 2.25, 2.5 , 2.75, 3.  , 3.  , 3.  , 3.  ],
       [2.5 , 2.75, 3.  , 3.25, 3.5 , 3.5 , 3.5 , 3.5 ],
       [3.  , 3.25, 3.5 , 3.75, 4.  , 4.  , 4.  , 4.  ],
       [3.  , 3.25, 3.5 , 3.75, 4.  , 4.  , 4.  , 4.  ],
       [3.  , 3.25, 3.5 , 3.75, 4.  , 4.  , 4.  , 4.  ],
       [3.  , 3.25, 3.5 , 3.75, 4.  , 4.  , 4.  , 4.  ]], dtype=float32)

# Useful Links

### [Official Doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling2D)